name: edu_quiz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  is_first_run: ^1.0.0

  #Firebase
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  firebase_remote_config: ^4.0.1

  #Modular e Bloc
  flutter_modular: ^5.0.3
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  #Armazenar dados 
  hive: ^2.2.3
  shared_preferences: ^2.1.0
  path_provider: ^2.0.11

  #Verificar internet
  connectivity_plus: ^2.3.0
  internet_connection_checker: ^1.0.0+1

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#fccb14"
  image: assets/images/icon.png
  fullscreen: true
  android: true
  ios: true
  android_screen_orientation: portrait

# Ao mudar de icone é necessário rodar:
# flutter pub get
# flutter pub run flutter_launcher_icons -f app-icon
# flutter pub get
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#fccb14" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/app-icon.png"



flutter:

  uses-material-design: true


  assets:
    - assets/images/app-icon.png

